### ISSUE TITLE
Database SQL ?

### ISSUE THREAD

**Issue by steffanjensen** [gexxxter/coinHiveMiner#1]
Hi where do I download the Database SQL ?

**Comment by gexxxter** [comment]
just added schema.sql

Keep in mind that this is a little hobby project and may not be continued.
But I'm happy for any improvement suggestions.

**Comment by steffanjensen** [comment]
Thanks man awesome got it to work I still have a problem with the cron collect balance this is the error

Fatal error: Call to a member function bind_param() on boolean in /home*/***/public_html/*****.com/b/cron/collectBalance.php on line 17

**Comment by gexxxter** [comment]
The cron is broken for now but it isn´t needed anyway.
I added it to reduce the load on the coinHive Api.
I maybe fix it next weekend.
