### ISSUE TITLE
Updating web stats

### ISSUE THREAD

**Issue by bqgam** [gexxxter/coinHiveMiner#2]
Is there any special requirements for php version, file permissions, mysql...
Stats for users are updating in coin-hive dashboard but nothing happens with the stats in the miner page (pool shares, pool hashes, top 10, etc)
The problem exist in XAMP and also on 000webhost.
The only errors i'm getting in xamp are:
undefined variable: dbuser (dbpass, dbname)
DB is created and user, pass and name are in the config.php

**Comment by gexxxter** [comment]
Oh snap I screwed up the config.php.

Fixed it, thanks for the hint!
It should work now
