### ISSUE TITLE
Chart Top Users

### ISSUE THREAD

**Issue by sinnatrix** [gexxxter/coinHiveMiner#9]
Btw uw made a great job doing this thnx for that but i need ur help
I cant make it work the Chart of users and the top users. it just doesnt show the users . thxn again

**Comment by gexxxter** [comment]
Could you pls call api/checkConnections.php in your browser and post the response here.
Or if your server is accessible from the internet post the address here and I will take a look

**Comment by kriptoblak** [comment]
When mining make sure to type in your username under "Username optional" field.
And to have cron job enabled to `/usr/bin/php -q /home/username/domain/cron/collectBalance.php >/dev/null`
